### ISSUE TITLE
Feature request: ProfileSwitcher support

### ISSUE THREAD

**Issue by LadnerJamie** [parnic/MMM-Unsplash#1]
I was wondering if you could add support for the MMM-ProfileSwitcher module? 

I am using my MagicMirror as a photoframe and am using your module as the background wallpaper which works great! I would love to be able to have the wallpaper change to suit the profile that is shown. If you're mot familiar with MMM-ProfilesSwitcher the link at github is here [https://github.com/tosti007/MMM-ProfileSwitcher]. 

Thanks for forking the Randomphoto module I really like being able to specify collections to show.

**Comment by parnic** [comment]
Interesting. I hadn't seen the profile switcher thing. I'll see what I can do.

**Comment by parnic** [comment]
See if the new "divName" config property (described in the updated readme) works for you. I was able to use it to successfully toggle between 2 Unsplash module instances on different profiles.

**Comment by LadnerJamie** [comment]
That's great! I'll give it a shot this weekend. Thanks for looking at it so quickly.
________________________________
