### ISSUE TITLE
Comstant image requst

### ISSUE THREAD

**Issue by kazanjig** [parnic/MMM-Unsplash#2]
I just installed the module for the first time and, after successfully retrieving an image, it continues to request very rapidly (on the order of 100/s) and exhausts all remaining requests for the hour...

Here's some of the error log:

`random Failed to load resource: the server responded with a status of 403 ()
random Failed to load resource: the server responded with a status of 403 ()
random Failed to load resource: the server responded with a status of 403 ()
MMM-Unsplash.js:51 GET https://api.unsplash.com/photos/random?collections=369966%2C1240111%2C1136512%2C629911%2C150672%2C920773&w=1080&h=1920&orientation=portrait 403 ()
load @ MMM-Unsplash.js:51
(anonymous) @ MMM-Unsplash.js:54
MMM-Unsplash.js:51 GET https://api.unsplash.com/photos/random?collections=369966%2C1240111%2C1136512%2C629911%2C150672%2C920773&w=1080&h=1920&orientation=portrait 403 ()
load @ MMM-Unsplash.js:51
(anonymous) @ MMM-Unsplash.js:54
MMM-Unsplash.js:51 GET https://api.unsplash.com/photos/random?collections=369966%2C1240111%2C1136512%2C629911%2C150672%2C920773&w=1080&h=1920&orientation=portrait 403 ()
load @ MMM-Unsplash.js:51
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53
(anonymous) @ MMM-Unsplash.js:54
MMM-Unsplash.js:51 GET https://api.unsplash.com/photos/random?collections=369966%2C1240111%2C1136512%2C629911%2C150672%2C920773&w=1080&h=1920&orientation=portrait 403 ()
load @ MMM-Unsplash.js:51
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53
(anonymous) @ MMM-Unsplash.js:54
MMM-Unsplash.js:51 GET https://api.unsplash.com/photos/random?collections=369966%2C1240111%2C1136512%2C629911%2C150672%2C920773&w=1080&h=1920&orientation=portrait 403 ()
load @ MMM-Unsplash.js:51
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53
(anonymous) @ MMM-Unsplash.js:54
setTimeout (async)
load @ MMM-Unsplash.js:53`

**Comment by parnic** [comment]
What is your `updateInterval` config set to? By default the script will update every 30 minutes (which is working correctly for me).

**Comment by kazanjig** [comment]
30000 (5 min) which still will put me nowhere near the 50/hour max.

**Comment by parnic** [comment]
I'm not sure what to tell you; that doesn't happen for me. I set mine to 30000 for testing and it's waiting 5 minutes before the next update.

**Comment by kazanjig** [comment]
Doh! Did I say 30000? I meant '30000'. Now to wait another 55 minutes to see that glorious eye candy.
