### ISSUE TITLE
Image only shows on part of screen

### ISSUE THREAD

**Issue by s1h4d0w** [parnic/MMM-Unsplash#3]
I just set up Magic Mirror and this was the first module I tried installing. Installed correctly as far as I'm aware. I navigated to the modules folder, cloned the git, then configured the module in config.js.

When MM starts the image covers about 60% of the left side of the screen. I at first thought this might be an issue with resolution so I set the width, height and orientation but it seems like it's loading portrait images, even with all that configured. As a wild guess I tried putting the width and height between quotes to see if it liked a string better, but no luck. Is there no way to force landscape images?

Here's how it looks:

![2019-06-02-203352_1920x1080_scrot](https://user-images.githubusercontent.com/5654654/58765837-5975b700-8577-11e9-9081-8101e12801df.png)

This is my config:
```
{
	module: 'MMM-Unsplash',
	position: 'fullscreen_below',
	width: 1920,
	height: 1080,
	orientation: 'landscape',
	config: {
		collections: '138884',
		apiKey: 'redacted'			
	}
},
```

**Comment by parnic** [comment]
`width`, `height`, and `orientation` need to be specified inside `config` for this to work. :)

**Comment by s1h4d0w** [comment]
I'm an idiot, thanks for the quick reply!
