### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by ykuzmycz** [parnic/MMM-Unsplash#4]
Without any changes to my MM install Unsplash stopped working.  Checked the API settings, not locked out.  Any other avenues of investigation?

**Comment by ykuzmycz** [comment]
API changed it seems.  obj.urls.custom is no longer an option (line 44).  Changed this to obj.urls.raw and it works.

**Comment by parnic** [comment]
Thanks - will get a fix pushed!

**Comment by ykuzmycz** [comment]
My pleasure - happy to help.  I "think" that's all that's needed (seems to be working for me and taking width and height).  Funny that the API docs say custom was deprecated ages ago and kept working.  :)  got to love that!

**Comment by ykuzmycz** [comment]
This may need to be reopened or reviewed.  MM is now failing with memory issues (nothing else changed).  It may be that using "raw" is the wrong approach.

**Comment by parnic** [comment]
> This may need to be reopened or reviewed. MM is now failing with memory issues (nothing else changed). It may be that using "raw" is the wrong approach.

Hmm, mine hasn't had these issues. I run on an RPi4, though. My change is using the Unsplash API recommendation of the RAW URL plus a `w` query parameter to specify the width of the image to pull. Is that what you're using?

**Comment by ykuzmycz** [comment]
yup, I've only changed the "raw" element.  The code puts in a default value for w

my config:

{
			module: 'MMM-Unsplash',
			position: 'fullscreen_below',
			config: {
				collections: '827743',
				apiKey: 'XXXX'
			}
		}

**Comment by parnic** [comment]
Not sure I'm following - are you using my code or some local changes you made? This is what my commit changed:
https://github.com/parnic/MMM-Unsplash/blob/9e606b78b7e0ad48521196179e269b96bc3a09a3/MMM-Unsplash.js#L44
although now that I look at it, that `&` may need to be a `?` if this `raw` doesn't return a URL with a parameter already on it. I thought it did, but maybe not?

**Comment by ykuzmycz** [comment]
I didn't refresh from git I made a local change.  Damn.  I missed the w parameter there.  (kicking myself)

That will teach me.

**Comment by ykuzmycz** [comment]
I think you might be right about ? versus &.  Just reading through the API docs now.

**Comment by ykuzmycz** [comment]
https://unsplash.com/documentation#get-a-random-photo

seems your approach is correct. We should be good.

**Comment by parnic** [comment]
It definitely should be a `?` instead of an `&`, but it seems to work as-is, so I'm not sure if I should do anything or not.

**Comment by ykuzmycz** [comment]
Not sure.  Check out below:

![image](https://user-images.githubusercontent.com/56328524/110871118-c44f3880-829b-11eb-9a6b-a8b6b26b42a6.png)

Seems the API call doesn't require the ?

**Comment by parnic** [comment]
Yeah, that's why I did it that way in the first place. In those examples, the `raw` image already had a `?` in the string. In our case, the `raw` url returned from the random photos doesn't have a `?` in it already, so presumably we need to include one. But maybe Chrome just does it for us? I watched the network traffic on the MM and it is definitely returning an image with the appropriate width. 🤷‍♂️

**Comment by ykuzmycz** [comment]
@parnic - is your height working fine?  Mine seems to cut off and not fill the full screen oddly.

**Comment by parnic** [comment]
I haven't noticed any height issues, but there is an `h` parameter that can be passed to the same URL.

**Comment by ykuzmycz** [comment]
Yeah. I’m passing it in. I wonder if the api doesn’t stretch the image if it’s not tall enough (shrink but not stretch). I might have to find another collection with larger images.

**Comment by ykuzmycz** [comment]
@parnic heads up.  I locally changed the code to pass in h instead of w.  With w my image was being cut at the bottom.  It's as if the image wasn't being stretched to fit within 1920x1080 (portrait).  By passing in h it forces the height instead.  I went through all my css, oddly just making that change fixed it.

**Comment by parnic** [comment]
I messed around with this a lot today, and it looks like the photos endpoint no longer handles the w/h parameters in the initial request for a random photo from a collection. So, you're not guaranteed to get back images that match the width/height you want. They seem to want you to specify a "fit" mode for how the photo dimensions you request will fit the output size you want.

In my random test case this morning, it gave me a 1200x1760 image for my 1200x1920 display. Asking this image to fit width would cause blank pixels at the bottom, while asking it to fit height would crop pixels from the right.

So I'm not sure if there's anything we can realistically do to prevent cropping when the request is not guaranteed to return images matching the specific desired aspect ratio. I think I'm just going to allow unsplash to do the cropping in an effort to ensure that the image fits the full screen with no blank areas. This can result in cropped edges, but the image will be centered and will not have blanks at the bottom or right. This could be a config parameter, but the specifics are a little annoying to convey, so cropping feels like a good starting point.

That is: using w=[width]&h=[height]&fit=crop. https://docs.imgix.com/apis/rendering/size/fit
